/* This is a GENERATED file. */
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "gwymoduletypes.h"
#include "./gwymodule-file.h"
GType
gwy_module_file_error_get_type(void)
{
    static GType etype = 0;

    if (etype == 0) {
        static const GEnumValue values[] = {
            { GWY_MODULE_FILE_ERROR_CANCELED, "GWY_MODULE_FILE_ERROR_CANCELED", "canceled" },
            { GWY_MODULE_FILE_ERROR_CANCELLED, "GWY_MODULE_FILE_ERROR_CANCELLED", "cancelled" },
            { GWY_MODULE_FILE_ERROR_UNIMPLEMENTED, "GWY_MODULE_FILE_ERROR_UNIMPLEMENTED", "unimplemented" },
            { GWY_MODULE_FILE_ERROR_IO, "GWY_MODULE_FILE_ERROR_IO", "io" },
            { GWY_MODULE_FILE_ERROR_DATA, "GWY_MODULE_FILE_ERROR_DATA", "data" },
            { GWY_MODULE_FILE_ERROR_INTERACTIVE, "GWY_MODULE_FILE_ERROR_INTERACTIVE", "interactive" },
            { GWY_MODULE_FILE_ERROR_SPECIFIC, "GWY_MODULE_FILE_ERROR_SPECIFIC", "specific" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static("GwyModuleFileError", values);
    }
    return etype;
}
#include "./gwymoduleenums.h"
GType
gwy_file_operation_type_get_type(void)
{
    static GType etype = 0;

    if (etype == 0) {
        static const GFlagsValue values[] = {
            { GWY_FILE_OPERATION_DETECT, "GWY_FILE_OPERATION_DETECT", "detect" },
            { GWY_FILE_OPERATION_LOAD, "GWY_FILE_OPERATION_LOAD", "load" },
            { GWY_FILE_OPERATION_SAVE, "GWY_FILE_OPERATION_SAVE", "save" },
            { GWY_FILE_OPERATION_EXPORT, "GWY_FILE_OPERATION_EXPORT", "export" },
            { GWY_FILE_OPERATION_MASK, "GWY_FILE_OPERATION_MASK", "mask" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static("GwyFileOperationType", values);
    }
    return etype;
}
GType
gwy_tool_switch_event_get_type(void)
{
    static GType etype = 0;

    if (etype == 0) {
        static const GEnumValue values[] = {
            { GWY_TOOL_SWITCH_WINDOW, "GWY_TOOL_SWITCH_WINDOW", "window" },
            { GWY_TOOL_SWITCH_TOOL, "GWY_TOOL_SWITCH_TOOL", "tool" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static("GwyToolSwitchEvent", values);
    }
    return etype;
}
GType
gwy_run_type_get_type(void)
{
    static GType etype = 0;

    if (etype == 0) {
        static const GFlagsValue values[] = {
            { GWY_RUN_NONE, "GWY_RUN_NONE", "none" },
            { GWY_RUN_NONINTERACTIVE, "GWY_RUN_NONINTERACTIVE", "noninteractive" },
            { GWY_RUN_INTERACTIVE, "GWY_RUN_INTERACTIVE", "interactive" },
            { GWY_RUN_IMMEDIATE, "GWY_RUN_IMMEDIATE", "immediate" },
            { GWY_RUN_MASK, "GWY_RUN_MASK", "mask" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static("GwyRunType", values);
    }
    return etype;
}
#include "./gwymoduleloader.h"
GType
gwy_module_error_get_type(void)
{
    static GType etype = 0;

    if (etype == 0) {
        static const GEnumValue values[] = {
            { GWY_MODULE_ERROR_NAME, "GWY_MODULE_ERROR_NAME", "name" },
            { GWY_MODULE_ERROR_DUPLICATE, "GWY_MODULE_ERROR_DUPLICATE", "duplicate" },
            { GWY_MODULE_ERROR_OPEN, "GWY_MODULE_ERROR_OPEN", "open" },
            { GWY_MODULE_ERROR_QUERY, "GWY_MODULE_ERROR_QUERY", "query" },
            { GWY_MODULE_ERROR_ABI, "GWY_MODULE_ERROR_ABI", "abi" },
            { GWY_MODULE_ERROR_INFO, "GWY_MODULE_ERROR_INFO", "info" },
            { GWY_MODULE_ERROR_REGISTER, "GWY_MODULE_ERROR_REGISTER", "register" },
            { GWY_MODULE_ERROR_NESTING, "GWY_MODULE_ERROR_NESTING", "nesting" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static("GwyModuleError", values);
    }
    return etype;
}

/* Generated data ends here */

