/* This is a GENERATED file. */
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __GWY_MODULE_TYPES_H__
#define __GWY_MODULE_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType gwy_module_file_error_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_MODULE_FILE_ERROR (gwy_module_file_error_get_type())
GType gwy_file_operation_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_FILE_OPERATION_TYPE (gwy_file_operation_type_get_type())
GType gwy_tool_switch_event_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_TOOL_SWITCH_EVENT (gwy_tool_switch_event_get_type())
GType gwy_run_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_RUN_TYPE (gwy_run_type_get_type())
GType gwy_module_error_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_MODULE_ERROR (gwy_module_error_get_type())
G_END_DECLS

#endif /* __GWY_MODULE_TYPES_H__ */

/* Generated data ends here */

