/* This is a GENERATED file. */
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __GWY_APP_TYPES_H__
#define __GWY_APP_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType gwy_app_what_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_APP_WHAT (gwy_app_what_get_type())
GType gwy_app_page_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_APP_PAGE (gwy_app_page_get_type())
GType gwy_data_item_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_DATA_ITEM (gwy_data_item_get_type())
GType gwy_visibility_reset_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_VISIBILITY_RESET_TYPE (gwy_visibility_reset_type_get_type())
GType gwy_data_watch_event_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_DATA_WATCH_EVENT_TYPE (gwy_data_watch_event_type_get_type())
GType gwy_dialog_outcome_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_DIALOG_OUTCOME (gwy_dialog_outcome_get_type())
GType gwy_preview_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_PREVIEW_TYPE (gwy_preview_type_get_type())
GType gwy_response_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_RESPONSE_TYPE (gwy_response_type_get_type())
GType gwy_text_header_error_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_TEXT_HEADER_ERROR (gwy_text_header_error_get_type())
GType gwy_synth_response_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_SYNTH_RESPONSE_TYPE (gwy_synth_response_type_get_type())
GType gwy_synth_dims_param_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_SYNTH_DIMS_PARAM (gwy_synth_dims_param_get_type())
GType gwy_synth_dims_flags_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_SYNTH_DIMS_FLAGS (gwy_synth_dims_flags_get_type())
GType gwy_synth_update_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_SYNTH_UPDATE_TYPE (gwy_synth_update_type_get_type())
GType gwy_preview_surface_flags_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_PREVIEW_SURFACE_FLAGS (gwy_preview_surface_flags_get_type())
GType gwy_plain_tool_changed_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_PLAIN_TOOL_CHANGED (gwy_plain_tool_changed_get_type())
GType gwy_results_export_style_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_RESULTS_EXPORT_STYLE (gwy_results_export_style_get_type())
GType gwy_tool_response_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_TOOL_RESPONSE_TYPE (gwy_tool_response_type_get_type())
GType gwy_help_flags_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_HELP_FLAGS (gwy_help_flags_get_type())
GType gwy_app_logging_flags_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_APP_LOGGING_FLAGS (gwy_app_logging_flags_get_type())
GType gwy_menu_sens_flags_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_MENU_SENS_FLAGS (gwy_menu_sens_flags_get_type())
GType gwy_app_settings_error_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_APP_SETTINGS_ERROR (gwy_app_settings_error_get_type())
GType gwy_data_error_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_DATA_ERROR (gwy_data_error_get_type())
GType gwy_data_validate_flags_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_DATA_VALIDATE_FLAGS (gwy_data_validate_flags_get_type())
G_END_DECLS

#endif /* __GWY_APP_TYPES_H__ */

/* Generated data ends here */

