/* This is a GENERATED file. */
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __GWYDRAW_TYPES_H__
#define __GWYDRAW_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType gwy_rendering_target_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_RENDERING_TARGET (gwy_rendering_target_get_type())
G_END_DECLS

#endif /* __GWYDRAW_TYPES_H__ */

/* Generated data ends here */

