/* This is a GENERATED file. */
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "gwydrawtypes.h"
#include "./gwydrawenums.h"
GType
gwy_rendering_target_get_type(void)
{
    static GType etype = 0;

    if (etype == 0) {
        static const GEnumValue values[] = {
            { GWY_RENDERING_TARGET_SCREEN, "GWY_RENDERING_TARGET_SCREEN", "screen" },
            { GWY_RENDERING_TARGET_PIXMAP_IMAGE, "GWY_RENDERING_TARGET_PIXMAP_IMAGE", "pixmap-image" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static("GwyRenderingTarget", values);
    }
    return etype;
}

/* Generated data ends here */

